micronaut:
  application:
    name: Sample APP

datasources:
  default:
    url: jdbc:qp:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.quickperf.micronaut.micronauttest.sql.QuickperfDriver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2